from typing import List
from models import Command


def get_windows_commands() -> List[Command]:
    """
    Retorna comandos específicos do Windows (mais de 50 comandos).
    """
    return [
        # ========== SISTEMA ==========
        Command(
            key="1",
            name="Painel de Controle (clássico)",
            command="control",
            category="Sistema",
            description="Abre o Painel de Controle clássico do Windows com todas as configurações do sistema.",
            requires_admin=False,
        ),
        Command(
            key="2",
            name="Gerenciador de Dispositivos",
            command="devmgmt.msc",
            category="Sistema",
            description="Gerencia drivers e dispositivos de hardware conectados ao computador.",
            requires_admin=True,
        ),
        Command(
            key="3",
            name="Serviços do Windows",
            command="services.msc",
            category="Sistema",
            description="Gerencia serviços do Windows (iniciar, parar, configurar inicialização automática).",
            requires_admin=True,
        ),
        Command(
            key="4",
            name="Informações do Sistema",
            command="msinfo32",
            category="Sistema",
            description="Exibe informações detalhadas sobre hardware, componentes e ambiente do sistema.",
            requires_admin=False,
        ),
        Command(
            key="5",
            name="Configuração do Sistema (msconfig)",
            command="msconfig",
            category="Sistema",
            description="Configura inicialização, serviços, boot e ferramentas de diagnóstico do Windows.",
            requires_admin=True,
        ),
        Command(
            key="6",
            name="Gerenciador de Tarefas",
            command="taskmgr",
            category="Sistema",
            description="Monitora processos, desempenho, CPU, memória e encerra tarefas não responsivas.",
            requires_admin=False,
        ),
        Command(
            key="7",
            name="Editor de Registro (regedit)",
            command="regedit",
            category="Sistema",
            description="Editor do registro do Windows para configurações avançadas do sistema.",
            requires_admin=True,
            is_critical=True,
        ),
        Command(
            key="8",
            name="Política de Grupo Local (gpedit)",
            command="gpedit.msc",
            category="Sistema",
            description="Edita políticas de grupo locais para configurações de segurança e sistema.",
            requires_admin=True,
        ),
        Command(
            key="9",
            name="Monitor de Recursos",
            command="resmon",
            category="Sistema",
            description="Monitora uso de CPU, memória, disco e rede em tempo real com detalhes por processo.",
            requires_admin=False,
        ),
        Command(
            key="10",
            name="Visualizador de Eventos",
            command="eventvwr.msc",
            category="Sistema",
            description="Visualiza logs de eventos do sistema, segurança, aplicativos e erros.",
            requires_admin=False,
        ),
        Command(
            key="11",
            name="Gerenciamento do Computador",
            command="compmgmt.msc",
            category="Sistema",
            description="Console centralizado com Visualizador de Eventos, Discos, Serviços e mais.",
            requires_admin=True,
        ),
        Command(
            key="12",
            name="Limpeza de Disco",
            command="cleanmgr",
            category="Sistema",
            description="Remove arquivos temporários e desnecessários para liberar espaço em disco.",
            requires_admin=False,
        ),
        Command(
            key="13",
            name="Desfragmentador de Disco",
            command="dfrgui",
            category="Sistema",
            description="Otimiza e desfragmenta unidades de disco para melhor desempenho.",
            requires_admin=True,
        ),

        # ========== REDE ==========
        Command(
            key="R1",
            name="Conexões de Rede",
            command="ncpa.cpl",
            category="Rede",
            description="Gerencia adaptadores de rede, configurações de IP, Wi-Fi e Ethernet.",
            requires_admin=False,
        ),
        Command(
            key="R2",
            name="Status de Rede (Configurações)",
            command="start ms-settings:network",
            category="Rede",
            description="Abre configurações modernas de rede do Windows 10/11.",
            requires_admin=False,
        ),
        Command(
            key="R3",
            name="Teste de Conexão (ping google)",
            command="ping 8.8.8.8 -n 4",
            category="Rede",
            description="Testa conectividade com a internet através do DNS do Google.",
            requires_admin=False,
        ),
        Command(
            key="R4",
            name="Configuração IP (ipconfig)",
            command="ipconfig /all",
            category="Rede",
            description="Exibe todas as configurações de rede TCP/IP do computador.",
            requires_admin=False,
        ),
        Command(
            key="R5",
            name="Renovar IP (DHCP)",
            command="ipconfig /release && ipconfig /renew",
            category="Rede",
            description="Libera e renova o endereço IP obtido por DHCP.",
            requires_admin=True,
        ),
        Command(
            key="R6",
            name="Limpar Cache DNS",
            command="ipconfig /flushdns",
            category="Rede",
            description="Limpa o cache de DNS para resolver problemas de resolução de nomes.",
            requires_admin=True,
        ),
        Command(
            key="R7",
            name="Trace Route (google.com)",
            command="tracert google.com",
            category="Rede",
            description="Rastreia o caminho dos pacotes até o destino, mostrando todos os saltos.",
            requires_admin=False,
        ),
        Command(
            key="R8",
            name="Firewall do Windows",
            command="wf.msc",
            category="Rede",
            description="Configurações avançadas do Firewall do Windows com segurança avançada.",
            requires_admin=True,
        ),
        Command(
            key="R9",
            name="Teste de Porta (netstat)",
            command="netstat -ano",
            category="Rede",
            description="Lista todas as conexões de rede ativas e portas em escuta.",
            requires_admin=False,
        ),

        # ========== USUÁRIOS E SEGURANÇA ==========
        Command(
            key="U1",
            name="Contas de Usuário",
            command="control userpasswords2",
            category="Usuário",
            description="Gerencia contas de usuário, senhas e login automático.",
            requires_admin=True,
        ),
        Command(
            key="U2",
            name="Usuários e Grupos Locais",
            command="lusrmgr.msc",
            category="Usuário",
            description="Gerencia usuários e grupos locais do Windows (não disponível no Home).",
            requires_admin=True,
        ),
        Command(
            key="U3",
            name="Controle dos Pais",
            command="control /name Microsoft.ParentalControls",
            category="Usuário",
            description="Configura controle dos pais e restrições de conta.",
            requires_admin=True,
        ),
        Command(
            key="U4",
            name="Política de Segurança Local",
            command="secpol.msc",
            category="Usuário",
            description="Define políticas de senha, auditoria, direitos de usuário e segurança.",
            requires_admin=True,
        ),
        Command(
            key="U5",
            name="Gerenciador de Credenciais",
            command="control /name Microsoft.CredentialManager",
            category="Usuário",
            description="Gerencia senhas salvas para sites, aplicativos e redes.",
            requires_admin=False,
        ),

        # ========== INTERNET E NAVEGAÇÃO ==========
        Command(
            key="I1",
            name="Opções da Internet",
            command="inetcpl.cpl",
            category="Internet",
            description="Configurações de proxy, cookies, histórico e segurança do Internet Explorer.",
            requires_admin=False,
        ),
        Command(
            key="I2",
            name="Configurações de Proxy",
            command="start ms-settings:network-proxy",
            category="Internet",
            description="Configura servidor proxy para conexão com a internet.",
            requires_admin=False,
        ),

        # ========== FERRAMENTAS E DESENVOLVIMENTO ==========
        Command(
            key="T1",
            name="Prompt de Comando",
            command="cmd.exe",
            category="Ferramentas",
            description="Abre o prompt de comando do Windows para executar comandos CLI.",
            requires_admin=False,
        ),
        Command(
            key="T2",
            name="PowerShell",
            command="powershell.exe",
            category="Ferramentas",
            description="Abre o Windows PowerShell para automação e scripts avançados.",
            requires_admin=False,
        ),
        Command(
            key="T3",
            name="PowerShell (Admin)",
            command="powershell.exe",
            category="Ferramentas",
            description="Abre o Windows PowerShell com privilégios administrativos.",
            requires_admin=True,
        ),
        Command(
            key="T4",
            name="Windows Terminal",
            command="wt.exe",
            category="Ferramentas",
            description="Abre o Windows Terminal moderno (se instalado).",
            requires_admin=False,
        ),
        Command(
            key="T5",
            name="Bloco de Notas",
            command="notepad",
            category="Ferramentas",
            description="Editor de texto simples do Windows.",
            requires_admin=False,
        ),
        Command(
            key="T6",
            name="Paint",
            command="mspaint",
            category="Ferramentas",
            description="Editor de imagens básico do Windows.",
            requires_admin=False,
        ),
        Command(
            key="T7",
            name="Calculadora",
            command="calc",
            category="Ferramentas",
            description="Calculadora do Windows.",
            requires_admin=False,
        ),
        Command(
            key="T8",
            name="Ferramenta de Captura",
            command="snippingtool",
            category="Ferramentas",
            description="Captura screenshots de áreas da tela.",
            requires_admin=False,
        ),
        Command(
            key="T9",
            name="Recorte e Esboço",
            command="start ms-screenclip:",
            category="Ferramentas",
            description="Ferramenta moderna de captura de tela do Windows 10/11.",
            requires_admin=False,
        ),

        # ========== HARDWARE E DISCOS ==========
        Command(
            key="D1",
            name="Gerenciamento de Disco",
            command="diskmgmt.msc",
            category="Disco",
            description="Particiona, formata e gerencia discos e volumes.",
            requires_admin=True,
        ),
        Command(
            key="D2",
            name="Verificar Disco (chkdsk C:)",
            command="echo Execute: chkdsk C: /F && pause",
            category="Disco",
            description="Verifica e repara erros no disco (requer agendamento para disco do sistema).",
            requires_admin=True,
            is_critical=True,
        ),
        Command(
            key="D3",
            name="DirectX Diagnostic",
            command="dxdiag",
            category="Disco",
            description="Diagnóstico de componentes DirectX, gráficos e som.",
            requires_admin=False,
        ),

        # ========== PROGRAMAS E RECURSOS ==========
        Command(
            key="P1",
            name="Programas e Recursos",
            command="appwiz.cpl",
            category="Programas",
            description="Desinstala ou altera programas instalados no Windows.",
            requires_admin=False,
        ),
        Command(
            key="P2",
            name="Recursos do Windows",
            command="optionalfeatures",
            category="Programas",
            description="Ativa ou desativa recursos opcionais do Windows.",
            requires_admin=True,
        ),
        Command(
            key="P3",
            name="Apps e Recursos (Configurações)",
            command="start ms-settings:appsfeatures",
            category="Programas",
            description="Interface moderna para gerenciar aplicativos instalados.",
            requires_admin=False,
        ),

        # ========== ENERGIA E DESEMPENHO ==========
        Command(
            key="E1",
            name="Opções de Energia",
            command="powercfg.cpl",
            category="Energia",
            description="Configura planos de energia, suspensão e hibernação.",
            requires_admin=False,
        ),
        Command(
            key="E2",
            name="Monitor de Desempenho",
            command="perfmon",
            category="Energia",
            description="Monitora desempenho do sistema com gráficos e contadores personalizados.",
            requires_admin=False,
        ),
        Command(
            key="E3",
            name="Relatório de Bateria",
            command="powercfg /batteryreport && start battery-report.html",
            category="Energia",
            description="Gera relatório detalhado sobre o uso e saúde da bateria.",
            requires_admin=False,
        ),

        # ========== PERSONALIZAÇÃO ==========
        Command(
            key="PE1",
            name="Personalização",
            command="control /name Microsoft.Personalization",
            category="Personalização",
            description="Temas, cores, plano de fundo e tela de bloqueio.",
            requires_admin=False,
        ),
        Command(
            key="PE2",
            name="Configurações de Vídeo",
            command="desk.cpl",
            category="Personalização",
            description="Resolução de tela, múltiplos monitores e orientação.",
            requires_admin=False,
        ),
        Command(
            key="PE3",
            name="Sons do Sistema",
            command="mmsys.cpl",
            category="Personalização",
            description="Configura dispositivos de áudio e sons de eventos do sistema.",
            requires_admin=False,
        ),
        Command(
            key="PE4",
            name="Mouse e Touchpad",
            command="main.cpl",
            category="Personalização",
            description="Configura botões, velocidade do ponteiro e scroll.",
            requires_admin=False,
        ),
        Command(
            key="PE5",
            name="Teclado",
            command="control keyboard",
            category="Personalização",
            description="Taxa de repetição e delay de caracteres do teclado.",
            requires_admin=False,
        ),

        # ========== DATA E HORA ==========
        Command(
            key="DH1",
            name="Data e Hora",
            command="timedate.cpl",
            category="Data/Hora",
            description="Ajusta data, hora, fuso horário e sincronização com internet.",
            requires_admin=False,
        ),

        # ========== BACKUP E RESTAURAÇÃO ==========
        Command(
            key="B1",
            name="Backup e Restauração",
            command="sdclt",
            category="Backup",
            description="Configura backup automático de arquivos e restauração do sistema.",
            requires_admin=True,
        ),
        Command(
            key="B2",
            name="Restauração do Sistema",
            command="rstrui",
            category="Backup",
            description="Restaura o Windows para um ponto anterior no tempo.",
            requires_admin=True,
            is_critical=True,
        ),
        Command(
            key="B3",
            name="Criar Ponto de Restauração",
            command="SystemPropertiesProtection",
            category="Backup",
            description="Cria e gerencia pontos de restauração do sistema.",
            requires_admin=True,
        ),

        # ========== ACESSIBILIDADE ==========
        Command(
            key="A1",
            name="Central de Facilidade de Acesso",
            command="utilman",
            category="Acessibilidade",
            description="Ferramentas de acessibilidade: narrador, lupa, teclado na tela.",
            requires_admin=False,
        ),
        Command(
            key="A2",
            name="Lupa",
            command="magnify",
            category="Acessibilidade",
            description="Amplia áreas da tela para melhor visualização.",
            requires_admin=False,
        ),
        Command(
            key="A3",
            name="Teclado Virtual",
            command="osk",
            category="Acessibilidade",
            description="Teclado na tela para entrada sem teclado físico.",
            requires_admin=False,
        ),
    ]
